[server]
headless = true
enableCORS = false
maxUploadSize = 200
enableXsrfProtection = false
maxMessageSize = 200
clientPingTimeout = 120

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2E7D32"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#212121"
font = "sans serif"

